type Member {
    id: ID!
    firstname: String!
    lastname: String!
    email: String!
    password: String!
    city: String
    postal_code: String
    avatar: String
    categories: [Category!]!
    trainings: [Training!]!
    reviews: [Review!]!
}

input MemberInput {
    firstname: String
    lastname: String
    email: String
    password: String
    city: String
    postalCode: String
    avatar: String
}
