"Represents a member"
type Member {
  "ID of the member"
  id: ID!
  "First name of the member"
  firstname: String!
  "Last name of the member"
  lastname: String!
  "Email address of the member"
  email: EmailAddress!
  "Password of the member"
  password: String!
  "City where the member resides"
  city: String
  "Postal code of the member's location"
  postal_code: String
  "Avatar URL of the member"
  avatar: String
  "Categories the member is interested in"
  categories: [Category]
  "Trainings attended by the member"
  trainings: [Training]
  "Reviews given by the member"
  reviews: [Review]
  "Nearest organizations"
  nearestOrganizations: [Organization]
  "Creation time of the member"
  created_at: Date!
  "Region of the member"
  region: String!
}

"Input for creating or updating a member"
input MemberInput {
  "First name of the member"
  firstname: String
  "Last name of the member"
  lastname: String
  "Email address of the member"
  email: EmailAddress
  "Password of the member"
  password: String
    @constraint(
      pattern: "^(?=.*\\w)(?=.*\\d)(?=.*[@$!%*#?&])[\\w\\d@$!%*#?&]{8,}$"
    )
  "City where the member resides"
  city: String @constraint(maxLength: 255)
  "Postal code of the member's location"
  postalCode: String
    @constraint(
      pattern: "^0[1-9]\\d{3}|[1-8]\\d{4}|9[0-6]\\d{3}|9[78][12478]\\d{2}$"
    )
  "Avatar URL of the member"
  avatar: String
}
