type Organization {
    id: ID!
    name: String!
    email: String!
    password: String!
    phone_number: String!
    address: String!
    city: String!
    postal_code: String!
    siret: String!
    image: String
    url_site: String
    trainings: [Training!]
}

input OrganizationInput {
    name: String
    email: String
    password: String
    phoneNumber: String
    address: String
    city: String
    postalCode: String
    siret: String
    image: String
    urlSite: String
}
