type Organization {
    id: ID!
    name: String!
    email: String!
    password: String!
    phoneNumber: String!
    address: String!
    city: String!
    postalCode: String!
    siret: String!
    image: String
    urlSite: String
    trainings: [Training!]!
}

input OrganizationInput {
    name: String
    email: String
    password: String
    phoneNumber: String
    address: String
    city: String
    postalCode: String
    siret: String
    image: String
    urlSite: String
}
