"Represents an organization"
type Organization {
    "ID of the organization"
    id: ID!
    "Name of the organization"
    name: String!
    "Email address of the organization"
    email: String!
    "Password of the organization"
    password: String!
    "Description of the organization"
    description: String
    "Phone number of the organization"
    phone_number: String!
    "Address of the organization"
    address: String!
    "City where the organization is located"
    city: String!

    "Postal code of the organization's location"
    postal_code: String!
    "SIRET number of the organization"
    siret: String!
    "Image URL of the organization"
    image: String

    "Website URL of the organization"
    url_site: String
    "Trainings offered by the organization"
    trainings: [Training!]
}

"Input for creating or updating an organization"
input OrganizationInput {
    "Name of the organization"
    name: String
    "Email address of the organization"
    email: String
    "Password of the organization"
    password: String
    "Phone number of the organization"
    phoneNumber: String
    "Address of the organization"
    address: String
    "City where the organization is located"
    city: String
    "Postal code of the organization's location"
    postalCode: String
    "SIRET number of the organization"
    siret: String
    "Image URL of the organization"
    image: String
    "Website URL of the organization"
    urlSite: String
}
