"Represents a review"
type Review {
    "ID of the review"
    id: ID!
    "Rating given in the review"
    rating: Int!
    "Comment provided in the review"
    comment: String
    "Training associated with the review"
    training: Training!
    "Member who submitted the review"
    member: Member!
}

"Input for creating or updating a review"
input ReviewInput {
    "Rating to be given in the review"
    rating: Int
    "Comment to be provided in the review"
    comment: String
    "ID of the training associated with the review"
    trainingId: Int
    "ID of the member who submitted the review"
    memberId: Int
}
