type Training {
    id: ID!
    label: String!
    description: String!
    price: Float!
    duration: Int!
    dates: [Date!]!   
    excerpt: String!
    prerequisites: String
    program: String
    image: String
    organization: Organization!
    category: Category!
    members: [Member!]
    reviews: [Review!]
}

input TrainingInput {
    label: String
    description: String
    price: Float
    duration: Int
    startingDate: String
    endingDate: String
    excerpt: String
    prerequisites: String
    program: String
    image: String
    organizationId: Int
    categoryId: Int
}
